version: '3.4'

services:
  app:
    build:
      target: fpm-dev
    volumes:
      - ../..:/var/www/app:cached

  web:
    build:
      context: ../..
      target: nginx-dev
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ../..:/var/www/app:cached

  cron:
    build:
      target: cron-dev
    volumes:
      - ../..:/var/www/app:cached

  supervisor:
    build:
      target: supervisor-dev
    volumes:
      - ../..:/var/www/app:cached