version: '3.4'

services:
  app:
    build:
      target: fpm-prod

  web:
    build:
      context: ../..
      target: nginx-prod
    ports:
      - 80:80
      - 443:443

  cron:
    build:
      target: cron-prod

  supervisor:
    build:
      target: supervisor-prod